START TRANSACTION;

SET @@autocommit = 0; 

CREATE SCHEMA IF NOT EXISTS `BD_CHECKLISTA` DEFAULT CHARACTER SET UTF8 ;

USE `BD_CHECKLISTA`;

CREATE TABLE IF NOT EXISTS `BD_CHECKLISTA`.`CKL_001_OBJETIVO` (
	`ID`				INT 			NOT NULL AUTO_INCREMENT
	,`OBJETIVO`			VARCHAR(500)	NOT NULL
	,`ATIVO`			BIT 			NOT NULL
    ,`DTH_INCLUSAO`		DATETIME		NOT NULL
    ,`DTH_ALTERACAO`	DATETIME		NULL
    ,`DTH_CONCLUSAO`	DATETIME		NULL
    ,`DTH_INATIVACAO`	DATETIME		NULL
    
    , CONSTRAINT `PK_001` PRIMARY KEY(`ID`)
    
    
) ENGINE = INNODB;

CREATE TABLE IF NOT EXISTS `CKL_002_SUBOBJETIVOS`(
	`ID`				INT				NOT NULL AUTO_INCREMENT
    ,`ID_CKL_OBJETIVO`	INT 			NOT NULL
    ,`OBJETIVO`			VARCHAR(500)	NOT NULL
    ,`CHECK`			BIT				NOT NULL
	,`DTH_INCLUSAO`		DATETIME		NOT NULL
	,`DTH_ALTERACAO`	DATETIME		NULL
    ,`DTH_CONCLUSAO`	DATETIME		NULL
    ,`DTH_INATIVACAO`	DATETIME		NULL
    
    , CONSTRAINT `PK_002` PRIMARY KEY(`ID`)
    , CONSTRAINT `FK_002_001` 	
		FOREIGN KEY(`ID_CKL_OBJETIVO`) 
        REFERENCES `CKL_001_OBJETIVO`(`ID`)

) ENGINE = INNODB;


COMMIT;